2020-05-30 20:43:23,848 ERROR: Exception on /user/sagar [GET] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 131, in user
    return render_template('user.html', user=user, posts=posts.items, prev_url=prev_url, next_url=next_url)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\base.html", line 56, in template
    {% block content %} {% endblock %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2020-05-30 20:47:04,667 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 20:49:07,625 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 20:54:52,467 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:01:16,331 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:01:51,509 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:02:43,161 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:03:41,243 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:04:36,062 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:06:05,611 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:07:24,001 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:07:26,561 ERROR: Exception on /index [GET] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 36, in index
    return render_template('index.html', title = 'Home', form=form, posts=posts.items, next_url=next_url, prev_url = prev_url)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\HP\Desktop\AskWall\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 12, in block "body"
  File "C:\Users\HP\Desktop\AskWall\app\templates\base.html", line 27, in block "navbar"
    <li><a href="{{ url_for('explore') }}">explore</a></li>
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'user' instead?
2020-05-30 21:08:01,754 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:10:57,857 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:12:28,489 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:13:49,613 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:14:58,753 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:18:08,112 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:18:40,914 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:26:08,838 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
2020-05-30 21:26:30,561 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:50]
