2020-05-29 01:16:16,954 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\AskWall\app\routes.py", line 99, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP\Desktop\AskWall\app\email.py", line 24, in send_password_reset_email
    user = user, token= token))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\HP\anaconda3\envs\askwall\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\AskWall\app\templates\email\reset_password.html", line 7, in template
    <p>{{ url_for('reset_password'), token=token, _external=True }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2020-05-29 01:17:49,750 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
2020-05-29 01:17:56,721 INFO: Askwall startup [in C:\Users\HP\Desktop\AskWall\app\__init__.py:48]
